
level1 = [
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBB",
]

levels = [
    level1
]